# Generated by Django 3.2.5 on 2021-07-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='producto',
            new_name='product',
        ),
    ]
